CREATE TABLE players (
  id SERIAL PRIMARY KEY,
  player_name VARCHAR(50) NOT NULL,
  player_position VARCHAR(10) NOT NULL,
  player_team VARCHAR(10) NOT NULL,
)

CREATE TABLE team (
  id SERIAL PRIMARY KEY,
  player_name VARCHAR(50) NOT NULL,
  player_position VARCHAR(10) NOT NULL,
  player_team VARCHAR(10) NOT NULL,
)

CREATE TABLE fg (
  fg_id SERIAL PRIMARY KEY,
  player_id INT REFERENCES players(id) ON UPDATE CASCADE ON DELETE CASCADE,
  fg DECIMAL NOT NULL
)

CREATE TABLE ft (
  ft_id SERIAL PRIMARY KEY,
  player_id INT REFERENCES players (id) ON UPDATE CASCADE ON DELETE CASCADE,
  ft DECIMAL NOT NULL,
)

CREATE TABLE threes (
  threes_id SERIAL PRIMARY KEY,
  player_id INT REFERENCES players (id) ON UPDATE CASCADE ON DELETE CASCADE,
  threes INT NOT NULL,
)

CREATE TABLE pts (
  pts_id SERIAL PRIMARY KEY,
  player_id INT REFERENCES players (id) ON UPDATE CASCADE ON DELETE CASCADE,
  pts INT NOT NULL
)

CREATE TABLE reb (
  reb_id SERIAL PRIMARY KEY,
  player_id INT REFERENCES players (id) ON UPDATE CASCADE ON DELETE CASCADE,
  reb INT NOT NULL
)

CREATE TABLE ast (
  ast_id SERIAL PRIMARY KEY,
  player_id INT REFERENCES players (id) ON UPDATE CASCADE ON DELETE CASCADE,
  ast INT NOT NULL,
)

CREATE TABLE stl (
  stl_id SERIAL PRIMARY KEY,
  player_id INT REFERENCES players (id) ON UPDATE CASCADE ON DELETE CASCADE,
  stl INT NOT NULL,
)

CREATE TABLE blk (
  blk_id SERIAL PRIMARY KEY,
  player_id INT REFERENCES players (id) ON UPDATE CASCADE ON DELETE CASCADE,
  blk INT NOT NULL,
)

CREATE TABLE tov (
  tov_id SERIAL PRIMARY KEY,
  player_id INT REFERENCES players (id) ON UPDATE CASCADE ON DELETE CASCADE,
  tov INT NOT NULL
)

CREATE TABLE team_fg (
  tfg_id SERIAL PRIMARY KEY,
  player_id INT REFERENCES team (id) ON UPDATE CASCADE ON DELETE CASCADE,
  team_fg DECIMAL NOT NULL
)

CREATE TABLE team_ft (
  tft_id SERIAL PRIMARY KEY,
  player_id INT REFERENCES team (id) ON UPDATE CASCADE ON DELETE CASCADE,
  team_ft DECIMAL NOT NULL
)

CREATE TABLE team_threes (
  tthrees_id SERIAL PRIMARY KEY,
  player_id INT REFERENCES team (id) ON UPDATE CASCADE ON DELETE CASCADE,
  team_threes INT NOT NULL
)

CREATE TABLE team_pts (
  tpts_id SERIAL PRIMARY KEY,
  player_id INT REFERENCES team (id) ON UPDATE CASCADE ON DELETE CASCADE,
  team_pts INT NOT NULL
)

CREATE TABLE team_reb (
  treb_id SERIAL PRIMARY KEY,
  player_id INT REFERENCES team (id) ON UPDATE CASCADE ON DELETE CASCADE,
  team_reb INT NOT NULL
)

CREATE TABLE team_ast (
  tast_id SERIAL PRIMARY KEY,
  player_id INT REFERENCES team (id) ON UPDATE CASCADE ON DELETE CASCADE,
  team_ast INT NOT NULL
)

CREATE TABLE team_stl (
  tstl_id SERIAL PRIMARY KEY,
  player_id INT REFERENCES team (id) ON UPDATE CASCADE ON DELETE CASCADE,
  team_stl INT NOT NULL
)

CREATE TABLE team_blk (
  tblk_id SERIAL PRIMARY KEY,
  player_id INT REFERENCES team (id) ON UPDATE CASCADE ON DELETE CASCADE,
  team_blk INT NOT NULL
)

CREATE TABLE team_tov (
  ttov_id SERIAL PRIMARY KEY,
  player_id INT REFERENCES team (id) ON UPDATE CASCADE ON DELETE CASCADE,
  team_tov INT NOT ULL
)
